apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  replicas: {{ .Values.app.replicas }}
  selector: 
    matchLabels:
      chart: {{ template "fullname" . }}
      tier: api
  template:
    metadata:
      labels:
        chart: {{ template "fullname" . }}
        tier: api
    spec:
      imagePullSecrets:
      - name: podcast-api
      containers:
      - name: rpodcast-api
        image: "{{ .Values.imgrepo }}{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
          - yarn serve
        ports:
        - containerPort: {{ .Values.app.internalPort}}
        env: #TODO: improve to use json object
        - name  : NODE_ENV
          value : "production"
        - name  : MONGO_HOSTNAME
          value : "mongodb"
        - name  : MONGO_PORT
          value : "27017"
        - name  : MONGO_DATABASE
          value : "Icarusdev"
        - name  : PORT
          value : "5000"
        