---
imgrepo:

service:
  externalPort: 80
  clusterType: ClusterIP

image: podcast-api
imageTag: latest
imagePullPolicy: IfNotPresent

app:
  internalPort: 5000
  replicas: 2

ingress:
  enabled: true
  hosts:
  - rl.runnerslife.local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /

app_config_json: >-
  {
    "NODE_ENV": "dev",
    "MONGO_HOSTNAME": "mongodb",
    "MONGO_PORT": "27017",
    "BASE_URL": "//api.bld-02.ep.agw.oncp.cloud",
    "USE_MOCK": "false",
    "MOCK_BASE_URL": "//api.bld-02.ep.agw.oncp.cloud/mock",
    "MOCK_OAUTH_BASE_URL": "//api.bld-02.ep.agw.oncp.cloud/mock"
  }
